import React from "react";
import { Provider } from "react-redux";
import store from "../redux/store/store"; // Import your Redux store
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import ToastProvider from "@/providers/ToastProvider";
import { IBM_Plex_Mono } from "next/font/google";

import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";

const inter = IBM_Plex_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: any) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        <ReduxProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
